/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-11-11 22:46:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1541894845000L));
    _jspx_dependants.put("jar:file:/home/yassine/Bureau/J2EE/Eatogether-branche_darine_deploy_test/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write("label{\n");
      out.write("\n");
      out.write("color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.3.4/dist/leaflet.css\"\n");
      out.write("   integrity=\"sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==\"\n");
      out.write("   crossorigin=\"\"/>\n");
      out.write("\n");
      out.write("<script src=\"https://unpkg.com/leaflet@1.3.4/dist/leaflet.js\"\n");
      out.write("   integrity=\"sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA==\"\n");
      out.write("   crossorigin=\"\"></script>\n");
      out.write("  \n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700,900\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/simple-line-icons.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/themify-icons.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/rendezvous.css\">\n");
      out.write("   \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write(" \n");
      out.write("  function statusChangeCallback(response) {\n");
      out.write("  \n");
      out.write("    if (response.status === 'connected') {\n");
      out.write("    \tconsole.log('Logged in and authenticated');\n");
      out.write("   \n");
      out.write("    //\t window.location.href=\"Connexion?acces_token=\"+ response.authResponse.accessToken;\n");
      out.write("    \n");
      out.write("    //\tsetElements(true);\n");
      out.write("  \n");
      out.write("    } else {\n");
      out.write("    \tconsole.log('NOT Logged');\n");
      out.write("    //\tsetElements(false);\n");
      out.write("    //\tFB.login();\n");
      out.write("    \t\n");
      out.write("   //   document.getElementById('status').innerHTML = 'Please log ' +\n");
      out.write("    //    'into this app.';\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("  }\n");
      out.write("  \n");
      out.write("/*  function setElements(isLoggedIn){\n");
      out.write("\t  \n");
      out.write("\t  if(isLoggedIn){\n");
      out.write("          document.getElementById('fb_btn').style.display = 'none';\n");
      out.write("          document.getElementById('profile').style.display = 'block';\n");
      out.write("          document.getElementById('logout').style.display = 'block';\n");
      out.write("         \n");
      out.write("        } else {\n");
      out.write("          document.getElementById('fb_btn').style.display = 'block';\n");
      out.write("          document.getElementById('profile').style.display = 'none';\n");
      out.write("       document.getElementById('logout').style.display = 'none';\n");
      out.write("         \n");
      out.write("        }\n");
      out.write("\t  \n");
      out.write("  }*/\n");
      out.write("  \n");
      out.write("  function test(){\t\n");
      out.write("\t  FB.getLoginStatus(function(response) {\n");
      out.write("\t     \n");
      out.write("\t\t  if (response.status === 'connected') {\n");
      out.write("\t\t\t  window.location.href=\"Connexion?acces_token=\"+ response.authResponse.accessToken;}\n");
      out.write("\t\t  \n");
      out.write("\t    });\n");
      out.write("\t  \n");
      out.write("\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" \n");
      out.write("  function checkLoginState() {\n");
      out.write("    FB.getLoginStatus(function(response) {\n");
      out.write("      statusChangeCallback(response);\n");
      out.write("    });\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  window.fbAsyncInit = function() {\n");
      out.write("    FB.init({\n");
      out.write("      appId      : '717842305245487',\n");
      out.write("      cookie     : true,    \n");
      out.write("      xfbml      : true, \n");
      out.write("      version    : 'v3.1' \n");
      out.write("    });\n");
      out.write("\n");
      out.write("    FB.getLoginStatus(function(response) {\n");
      out.write("      statusChangeCallback(response);\n");
      out.write("    });\n");
      out.write("\n");
      out.write("  };\n");
      out.write("\n");
      out.write("  // Load the SDK asynchronously\n");
      out.write("  (function(d, s, id) {\n");
      out.write("    var js, fjs = d.getElementsByTagName(s)[0];\n");
      out.write("    if (d.getElementById(id)) return;\n");
      out.write("    js = d.createElement(s); js.id = id;\n");
      out.write("    js.src = \"https://connect.facebook.net/en_US/sdk.js\";\n");
      out.write("    fjs.parentNode.insertBefore(js, fjs);\n");
      out.write("  }(document, 'script', 'facebook-jssdk'));\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  function logout(){\n");
      out.write("\t  FB.logout();\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  \n");
      out.write("</script>\n");
      out.write("\t \n");
      out.write(" \t<script src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"js/recherche.js\"></script>\n");
      out.write("    <section class=\"slider d-flex align-items-center\">\n");
      out.write("        <!-- <img src=\"images/slider.jpg\" class=\"img-fluid\" alt=\"#\"> -->\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row d-flex justify-content-center\">\n");
      out.write("                <div class=\"col-md-12\">\n");
      out.write("                    <div class=\"slider-title_box\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-12\">\n");
      out.write("                                <div class=\"slider-content_wrap\">\n");
      out.write("                                \t<img class=\"img-responsive\" src=\"images/logo1.png\"><br>\n");
      out.write("                                    <h1>Eatogether</h1>\n");
      out.write("                                    <h5>Partagez vos repas préférés dans un cadre conviviale..</h5>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <form class=\"form-wrap mt-4\" method=\"post\" action=\"Connexion\" id=\"cnx\">\n");
      out.write("                        <br>\n");
      out.write("    \t\t\t\t\t\t\t\n");
      out.write("    \t\t\t\t\t\t\t<div class=\"row d-flex justify-content-center\">\n");
      out.write("    \t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("    \t\t\t\t\t\t\t\t    <input type=\"text\" id=\"pseudo\" name=\"pseudo\" placeholder=\"E-mail\" required=\"true\" class=\"btn-group1\"/>\n");
      out.write("    \t\t\t\t\t\t\t\t</div>\n");
      out.write("    \t\t\t\t\t\t\t</div>     \n");
      out.write("      \t\t\t\t\t\t\t<br>\n");
      out.write("     \t\t\t\t\t\t\t\t\n");
      out.write("   \t\t\t\t\t\t\t\t\t <div class=\"row d-flex justify-content-center\">\n");
      out.write("    \t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("      \t\t\t\t\t\t\t\t<input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Mot de Passe\" class=\"btn-group1\" required=\"true\"/>\n");
      out.write("      \t\t\t\t\t\t\t\t</div></div><br>\n");
      out.write("      \t\t\t\t\t\t\t\n");
      out.write("      \t\t\t\t\t\t\t\n");
      out.write("      \t\t\t\t\t\t\t\t\t<div class=\"row d-flex justify-content-center\">\n");
      out.write("    \t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("    \t\t\t\t\n");
      out.write("      \t\t\t\t\t\t\t\t\t <p class=\"message\"><label>Not registered?</label> <a href=\"inscription.jsp\">Create an account</a></p>\n");
      out.write("                                  \n");
      out.write("                                        <button type=\"submit\" class=\"btn-form\">Connexion<i class=\"pe-7s-angle-right\"></i></button>\n");
      out.write("                                  <div id=\"profile\">\n");
      out.write("\n");
      out.write("    <div  class=\"fb-login-button\" scope=\"public_profile,email,user_birthday,user_gender\" data-onlogin=\"test();\" data-max-rows=\"1\" data-size=\"large\" data-button-type=\"continue_with\" data-show-faces=\"false\" data-auto-logout-link=\"true\" data-use-continue-as=\"true\"></div> \n");
      out.write("\n");
      out.write("\t\t\t</div>  \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t  \n");
      out.write("                                        </div></div>\n");
      out.write("                                         </form><br><br><br>\n");
      out.write("                                         <img class=\"img-responsive\" src=\"images/foursquare1.png\"><br>\n");
      out.write("                                    </div>\n");
      out.write("                            </div>\n");
      out.write("                       </div>\n");
      out.write("                </div>\n");
      out.write("    </section>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
